package com.challenge.notifications.domain.enums;

public enum ErrorCode {
    INVALID_NOTIFICATION_ID,
    INVALID_EMAIL,
    INVALID_PHONE_NUMBER,
    INVALID_DEVICE_TOKEN,
    INVALID_SUBJECT,
    INVALID_MESSAGE_BODY,
    INVALID_NOTIFICATION,
    INVALID_NOTIFICATION_RESULT,
    PROVIDER_ERROR,
    CONFIGURATION_ERROR
}